version: '3.9'
services:
  web:
    build: .
    command: bash -c "rm -f rails_mysql_pj/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/rails_mysql_pj'
    ports:
      - '3000:3000'
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      MYSQL_PASSWORD: user_pass
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: user_pass
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
